/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DashboardStats = IDL.Record({
  'onlineDrivers' : IDL.Nat,
  'ridesToday' : IDL.Nat,
  'revenueToday' : IDL.Float64,
  'totalUsers' : IDL.Nat,
});
export const DriverPublic = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'earnings' : IDL.Float64,
  'vehicle' : IDL.Text,
  'rating' : IDL.Float64,
  'totalRides' : IDL.Nat,
});
export const RideStatus = IDL.Variant({
  'cancelada' : IDL.Null,
  'concluida' : IDL.Null,
  'em_andamento' : IDL.Null,
  'searching' : IDL.Null,
  'em_rota' : IDL.Null,
});
export const Ride = IDL.Record({
  'id' : IDL.Nat,
  'status' : RideStatus,
  'destination' : IDL.Text,
  'clientName' : IDL.Text,
  'fare' : IDL.Float64,
  'origin' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'durationMinutes' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const Features = IDL.Record({
  'shareRoute' : IDL.Bool,
  'showPriceBeforeAccept' : IDL.Bool,
  'scheduledRides' : IDL.Bool,
  'multipleDestinations' : IDL.Bool,
});
export const SettingsPublic = IDL.Record({
  'serviceFeePercent' : IDL.Float64,
  'features' : Features,
  'searchRadiusKm' : IDL.Float64,
  'minimumFare' : IDL.Float64,
  'acceptTimeoutSeconds' : IDL.Nat,
  'cancellationFee' : IDL.Float64,
  'perKm' : IDL.Float64,
  'perMinute' : IDL.Float64,
  'baseFare' : IDL.Float64,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'totalSpent' : IDL.Float64,
  'registrationDate' : IDL.Int,
  'totalRides' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDrivers' : IDL.Func([], [IDL.Vec(DriverPublic)], ['query']),
  'getRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
  'getSettings' : IDL.Func([], [SettingsPublic], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'toggleDriverOnline' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateSettings' : IDL.Func([SettingsPublic], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DashboardStats = IDL.Record({
    'onlineDrivers' : IDL.Nat,
    'ridesToday' : IDL.Nat,
    'revenueToday' : IDL.Float64,
    'totalUsers' : IDL.Nat,
  });
  const DriverPublic = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'earnings' : IDL.Float64,
    'vehicle' : IDL.Text,
    'rating' : IDL.Float64,
    'totalRides' : IDL.Nat,
  });
  const RideStatus = IDL.Variant({
    'cancelada' : IDL.Null,
    'concluida' : IDL.Null,
    'em_andamento' : IDL.Null,
    'searching' : IDL.Null,
    'em_rota' : IDL.Null,
  });
  const Ride = IDL.Record({
    'id' : IDL.Nat,
    'status' : RideStatus,
    'destination' : IDL.Text,
    'clientName' : IDL.Text,
    'fare' : IDL.Float64,
    'origin' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'durationMinutes' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const Features = IDL.Record({
    'shareRoute' : IDL.Bool,
    'showPriceBeforeAccept' : IDL.Bool,
    'scheduledRides' : IDL.Bool,
    'multipleDestinations' : IDL.Bool,
  });
  const SettingsPublic = IDL.Record({
    'serviceFeePercent' : IDL.Float64,
    'features' : Features,
    'searchRadiusKm' : IDL.Float64,
    'minimumFare' : IDL.Float64,
    'acceptTimeoutSeconds' : IDL.Nat,
    'cancellationFee' : IDL.Float64,
    'perKm' : IDL.Float64,
    'perMinute' : IDL.Float64,
    'baseFare' : IDL.Float64,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'totalSpent' : IDL.Float64,
    'registrationDate' : IDL.Int,
    'totalRides' : IDL.Nat,
  });
  
  return IDL.Service({
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDrivers' : IDL.Func([], [IDL.Vec(DriverPublic)], ['query']),
    'getRides' : IDL.Func([], [IDL.Vec(Ride)], ['query']),
    'getSettings' : IDL.Func([], [SettingsPublic], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'toggleDriverOnline' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateSettings' : IDL.Func([SettingsPublic], [], []),
  });
};

export const init = ({ IDL }) => { return []; };