/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'onlineDrivers' : bigint,
  'ridesToday' : bigint,
  'revenueToday' : number,
  'totalUsers' : bigint,
}
export interface DriverPublic {
  'id' : bigint,
  'name' : string,
  'isOnline' : boolean,
  'earnings' : number,
  'vehicle' : string,
  'rating' : number,
  'totalRides' : bigint,
}
export interface Features {
  'shareRoute' : boolean,
  'showPriceBeforeAccept' : boolean,
  'scheduledRides' : boolean,
  'multipleDestinations' : boolean,
}
export interface Ride {
  'id' : bigint,
  'status' : RideStatus,
  'destination' : string,
  'clientName' : string,
  'fare' : number,
  'origin' : string,
  'distanceKm' : number,
  'durationMinutes' : number,
  'timestamp' : bigint,
}
export type RideStatus = { 'cancelada' : null } |
  { 'concluida' : null } |
  { 'em_andamento' : null } |
  { 'searching' : null } |
  { 'em_rota' : null };
export interface SettingsPublic {
  'serviceFeePercent' : number,
  'features' : Features,
  'searchRadiusKm' : number,
  'minimumFare' : number,
  'acceptTimeoutSeconds' : bigint,
  'cancellationFee' : number,
  'perKm' : number,
  'perMinute' : number,
  'baseFare' : number,
}
export interface User {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'totalSpent' : number,
  'registrationDate' : bigint,
  'totalRides' : bigint,
}
export interface _SERVICE {
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDrivers' : ActorMethod<[], Array<DriverPublic>>,
  'getRides' : ActorMethod<[], Array<Ride>>,
  'getSettings' : ActorMethod<[], SettingsPublic>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'toggleDriverOnline' : ActorMethod<[bigint], boolean>,
  'updateSettings' : ActorMethod<[SettingsPublic], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];