/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Ride {
    id: bigint;
    status: RideStatus;
    destination: string;
    clientName: string;
    fare: number;
    origin: string;
    distanceKm: number;
    durationMinutes: number;
    timestamp: bigint;
}
export interface SettingsPublic {
    serviceFeePercent: number;
    features: Features;
    searchRadiusKm: number;
    minimumFare: number;
    acceptTimeoutSeconds: bigint;
    cancellationFee: number;
    perKm: number;
    perMinute: number;
    baseFare: number;
}
export interface DriverPublic {
    id: bigint;
    name: string;
    isOnline: boolean;
    earnings: number;
    vehicle: string;
    rating: number;
    totalRides: bigint;
}
export interface User {
    id: bigint;
    name: string;
    email: string;
    totalSpent: number;
    registrationDate: bigint;
    totalRides: bigint;
}
export interface DashboardStats {
    onlineDrivers: bigint;
    ridesToday: bigint;
    revenueToday: number;
    totalUsers: bigint;
}
export interface Features {
    shareRoute: boolean;
    showPriceBeforeAccept: boolean;
    scheduledRides: boolean;
    multipleDestinations: boolean;
}
export enum RideStatus {
    cancelada = "cancelada",
    concluida = "concluida",
    em_andamento = "em_andamento",
    searching = "searching",
    em_rota = "em_rota"
}
export interface backendInterface {
    getDashboardStats(): Promise<DashboardStats>;
    getDrivers(): Promise<Array<DriverPublic>>;
    getRides(): Promise<Array<Ride>>;
    getSettings(): Promise<SettingsPublic>;
    getUsers(): Promise<Array<User>>;
    toggleDriverOnline(id: bigint): Promise<boolean>;
    updateSettings(update: SettingsPublic): Promise<void>;
}
import type { Ride as _Ride, RideStatus as _RideStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDrivers(): Promise<Array<DriverPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrivers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrivers();
            return result;
        }
    }
    async getRides(): Promise<Array<Ride>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRides();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRides();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<SettingsPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return result;
        }
    }
    async toggleDriverOnline(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDriverOnline(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDriverOnline(arg0);
            return result;
        }
    }
    async updateSettings(arg0: SettingsPublic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
}
function from_candid_RideStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RideStatus): RideStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Ride_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ride): Ride {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RideStatus;
    destination: string;
    clientName: string;
    fare: number;
    origin: string;
    distanceKm: number;
    durationMinutes: number;
    timestamp: bigint;
}): {
    id: bigint;
    status: RideStatus;
    destination: string;
    clientName: string;
    fare: number;
    origin: string;
    distanceKm: number;
    durationMinutes: number;
    timestamp: bigint;
} {
    return {
        id: value.id,
        status: from_candid_RideStatus_n4(_uploadFile, _downloadFile, value.status),
        destination: value.destination,
        clientName: value.clientName,
        fare: value.fare,
        origin: value.origin,
        distanceKm: value.distanceKm,
        durationMinutes: value.durationMinutes,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelada: null;
} | {
    concluida: null;
} | {
    em_andamento: null;
} | {
    searching: null;
} | {
    em_rota: null;
}): RideStatus {
    return "cancelada" in value ? RideStatus.cancelada : "concluida" in value ? RideStatus.concluida : "em_andamento" in value ? RideStatus.em_andamento : "searching" in value ? RideStatus.searching : "em_rota" in value ? RideStatus.em_rota : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ride>): Array<Ride> {
    return value.map((x)=>from_candid_Ride_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
